repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --recursive
          - .

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
