name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Executes after build if request is pushing to main branch
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # Get into server and start docker compose
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/${{ secrets.REMOTE_SSH_USERNAME }}/Projects/Coordipai/web-server
            git pull origin main
            cd /home/${{ secrets.REMOTE_SSH_USERNAME }}/Projects
            docker compose up -d --no-deps --build --force-recreate coordipai-web-server
            docker image prune -af
